# Generated by Django 5.0.6 on 2024-07-27 15:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Tester', max_length=200)),
                ('file', models.FileField(upload_to=blog.models.upload_tester)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default Training', max_length=200)),
                ('file', models.FileField(upload_to=blog.models.upload_training)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_file_name', models.CharField(max_length=255)),
                ('training_file_name', models.CharField(max_length=255)),
                ('code_result_percent', models.CharField(max_length=10)),
                ('list_same_code', models.JSONField()),
                ('text_result_percent', models.CharField(max_length=10)),
                ('list_same_text', models.JSONField()),
                ('join_result_percent', models.CharField(max_length=10)),
            ],
        ),
    ]
